alias la='ls -a'
alias ll='ls -alh'
alias pactl-hdmi='pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:hdmi-stereo && pactl set-sink-port @DEFAULT_SINK@ hdmi-output-0'
alias xclip="xclip -selection c"
alias op="opencode"
alias rg="rg --no-ignore"
alias fd="fd -u"
alias audiosource='~/audiosource.sh'
alias git-pull-force='git fetch origin && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)'
alias nap="systemctl suspend"
alias shut="shutdown now"
