alias la='ls -a'
alias ll='ls -alh'
alias pactl-hdmi='pactl set-card-profile alsa_card.pci-0000_00_1f.3 output:hdmi-stereo && pactl set-sink-port @DEFAULT_SINK@ hdmi-output-0'
alias xclip="xclip -selection c"
alias op="opencode"
alias rg="rg --no-ignore"
alias fd="fd -u"
alias audiosource='~/audiosource.sh'
alias pi='pi -t read,bash,grep,find,ls'
